language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
before_script:
  - mkdir bin
  - cd bin
  - cmake ..
script:
- if [ $TRAVIS_OS_NAME == linux ]; make; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - cmake
branches:
  only:
  - xd_dev
  - "/^v\\d+\\./"
notifications:
  email: false
env:
  global:
  - LANG="en_US.UTF-8"
