version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image:
- Visual Studio 2017
- Previous Visual Studio 2017
configuration:
- Debug
- Release
- Mixed
platform:
- x64
- x86
before_build:
- cmd: git submodule update --init --recursive
build:
  project: src/engine.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: xrbuild.cmd
test: off
